# Generated by Django 4.2.3 on 2023-10-28 22:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0002_remove_hospital_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospital",
            name="phone",
            field=models.CharField(default=9999999999, max_length=10),
            preserve_default=False,
        ),
    ]
