# Generated by Django 4.2.3 on 2023-10-31 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0003_hospital_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="expected_arrival_date",
            field=models.DateField(null=True),
        ),
    ]
