# Generated by Django 4.2.3 on 2023-11-01 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bloodbank", "0006_remove_bloodbank_is_verified"),
        ("hospital", "0004_alter_request_expected_arrival_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hospital",
            name="is_verified",
        ),
        migrations.AddField(
            model_name="request",
            name="blood_bank",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bloodbank.bloodbank",
            ),
        ),
        migrations.AddField(
            model_name="request",
            name="is_accepted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="request",
            name="expected_arrival_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
