# Generated by Django 4.2.3 on 2023-11-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0005_remove_hospital_is_verified_request_blood_bank_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospital",
            name="image",
            field=models.ImageField(default=None, upload_to="signup/"),
        ),
    ]
