# Generated by Django 4.2.6 on 2023-10-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bloodbank", "0002_remove_bloodbank_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bloodbank",
            name="a_neg",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="bloodbank",
            name="a_pos",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="bloodbank",
            name="ab_neg",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="bloodbank",
            name="ab_pos",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="bloodbank",
            name="b_neg",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="bloodbank",
            name="b_pos",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="bloodbank",
            name="o_neg",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="bloodbank",
            name="o_pos",
            field=models.IntegerField(default=0),
        ),
    ]
