# Generated by Django 4.2.3 on 2023-10-31 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bloodbank", "0004_donation_is_liked"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="is_seen",
            field=models.BooleanField(default=False),
        ),
    ]
