# Generated by Django 4.2.3 on 2023-11-02 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bloodbank", "0006_remove_bloodbank_is_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="bloodbank",
            name="image",
            field=models.ImageField(default=None, upload_to="signup/"),
        ),
    ]
