# Generated by Django 4.2.3 on 2023-11-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bloodbank", "0007_bloodbank_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="first_save",
            field=models.BooleanField(default=False),
        ),
    ]
