# Generated by Django 4.2.6 on 2023-10-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("donor", "0002_remove_donor_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donor",
            name="gender",
            field=models.CharField(choices=[("M", "M"), ("F", "F")], max_length=6),
        ),
    ]
