# Generated by Django 4.2.3 on 2023-11-01 20:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("donor", "0003_alter_donor_gender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donor",
            name="is_verified",
        ),
    ]
