# Generated by Django 4.2.3 on 2023-11-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("donor", "0004_remove_donor_is_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="donor",
            name="image",
            field=models.ImageField(default=None, upload_to="signup/"),
        ),
    ]
