# Generated by Django 4.2.3 on 2023-11-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("donor", "0007_alter_donor_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donor",
            name="image",
            field=models.ImageField(default=None, upload_to="signup/"),
        ),
    ]
